name: Python Check

on: [push]

jobs:
  check:
    name: Check Python ${{ matrix.python_version }}
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.9", "3.10", "3.11"]
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64

      - name: Install Poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Run yapf
        run: poetry run yapf -r -d unlicense

      - name: Run mypy
        run: poetry run mypy --strict unlicense
